### ISSUE TITLE
Gain access for any user to use a bot

### ISSUE THREAD

**Issue by bekvizz** [rewired-gh/ichigo-bot#3]
### Hello!
I tried to share the bot with my friends, but it doesn't work for them. Logs saying, "WARN unauthorized access attempt user_id=...". How can I give access without explicitly typing every telegram ID of people I want to give it access to? Sorry for that type of communication, and thanks for your attention!

**Comment by rewired-gh** [comment]
You may try this configuration:

```toml
[[Blocklist]]
ExceptSessions = true # Block except none == Allow all
Sessions = [] # No session
ExceptModels = true # The same trick
Models = []
```

I'm glad this bot could help you. I hope this configuration resolves your issue.
